[2022-06-23 14:05:19,601] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-23 14:05:19,607] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-23 14:05:19,608] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-23 14:05:19,608] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-23 14:05:19,608] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-23 14:05:19,621] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-01-01 00:00:00+00:00
[2022-06-23 14:05:19,625] {standard_task_runner.py:52} INFO - Started process 297 to run task
[2022-06-23 14:05:19,628] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_to_gcs', 'local_to_gcs_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/01_data_ingestion_to_gcs.py', '--cfg-path', '/tmp/tmpm2w0_xon', '--error-file', '/tmp/tmp6mg__1jm']
[2022-06-23 14:05:19,628] {standard_task_runner.py:80} INFO - Job 182: Subtask local_to_gcs_task
[2022-06-23 14:05:19,662] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host 24ab0148fd1d
[2022-06-23 14:05:19,716] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_to_gcs
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T00:00:00+00:00
[2022-06-23 14:05:20,138] {python.py:173} INFO - Done. Returned value was: None
[2022-06-23 14:05:20,148] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion_to_gcs, task_id=local_to_gcs_task, execution_date=20200101T000000, start_date=20220623T140519, end_date=20220623T140520
[2022-06-23 14:05:20,200] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-23 14:05:20,245] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-06-23 15:00:31,694] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-23 15:00:31,700] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-23 15:00:31,700] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-23 15:00:31,700] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-23 15:00:31,700] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-23 15:00:31,710] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-01-01 00:00:00+00:00
[2022-06-23 15:00:31,715] {standard_task_runner.py:52} INFO - Started process 254 to run task
[2022-06-23 15:00:31,717] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_to_gcs', 'local_to_gcs_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/01_data_ingestion_to_gcs.py', '--cfg-path', '/tmp/tmpoudf1arh', '--error-file', '/tmp/tmpm52xbod9']
[2022-06-23 15:00:31,717] {standard_task_runner.py:80} INFO - Job 210: Subtask local_to_gcs_task
[2022-06-23 15:00:31,752] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host 9ac39f243003
[2022-06-23 15:00:31,801] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_to_gcs
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T00:00:00+00:00
[2022-06-23 15:00:32,661] {python.py:173} INFO - Done. Returned value was: None
[2022-06-23 15:00:32,680] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion_to_gcs, task_id=local_to_gcs_task, execution_date=20200101T000000, start_date=20220623T150031, end_date=20220623T150032
[2022-06-23 15:00:32,734] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-23 15:00:32,790] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-06-27 10:31:54,206] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-27 10:31:54,216] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-27 10:31:54,216] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 10:31:54,216] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-27 10:31:54,216] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 10:31:54,232] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-01-01 00:00:00+00:00
[2022-06-27 10:31:54,238] {standard_task_runner.py:52} INFO - Started process 232 to run task
[2022-06-27 10:31:54,241] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_to_gcs', 'local_to_gcs_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/01_data_ingestion_to_gcs.py', '--cfg-path', '/tmp/tmpovtnipjl', '--error-file', '/tmp/tmpvfghuwro']
[2022-06-27 10:31:54,242] {standard_task_runner.py:80} INFO - Job 335: Subtask local_to_gcs_task
[2022-06-27 10:31:54,293] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host ba54ad88b6ec
[2022-06-27 10:31:54,384] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_to_gcs
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T00:00:00+00:00
[2022-06-27 10:31:55,278] {python.py:173} INFO - Done. Returned value was: None
[2022-06-27 10:31:55,288] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion_to_gcs, task_id=local_to_gcs_task, execution_date=20200101T000000, start_date=20220627T103154, end_date=20220627T103155
[2022-06-27 10:31:55,335] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 10:31:55,371] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-06-27 13:13:12,997] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-27 13:13:13,002] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-27 13:13:13,002] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:13:13,002] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-27 13:13:13,002] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-27 13:13:13,012] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-01-01 00:00:00+00:00
[2022-06-27 13:13:13,017] {standard_task_runner.py:52} INFO - Started process 6415 to run task
[2022-06-27 13:13:13,019] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_to_gcs', 'local_to_gcs_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '371', '--raw', '--subdir', 'DAGS_FOLDER/01_data_ingestion_to_gcs.py', '--cfg-path', '/tmp/tmpvnzmsk8k', '--error-file', '/tmp/tmp2oc_w22o']
[2022-06-27 13:13:13,020] {standard_task_runner.py:80} INFO - Job 371: Subtask local_to_gcs_task
[2022-06-27 13:13:13,058] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host 78ff5d0f8165
[2022-06-27 13:13:13,111] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_to_gcs
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T00:00:00+00:00
[2022-06-27 13:13:13,579] {python.py:173} INFO - Done. Returned value was: None
[2022-06-27 13:13:13,590] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion_to_gcs, task_id=local_to_gcs_task, execution_date=20200101T000000, start_date=20220627T131312, end_date=20220627T131313
[2022-06-27 13:13:13,632] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-27 13:13:13,663] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-06-28 14:41:35,700] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-28 14:41:35,706] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-28 14:41:35,706] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 14:41:35,706] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-28 14:41:35,706] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 14:41:35,716] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-01-01 00:00:00+00:00
[2022-06-28 14:41:35,720] {standard_task_runner.py:52} INFO - Started process 139 to run task
[2022-06-28 14:41:35,722] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_to_gcs', 'local_to_gcs_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '490', '--raw', '--subdir', 'DAGS_FOLDER/01_data_ingestion_to_gcs.py', '--cfg-path', '/tmp/tmpl4kkg8se', '--error-file', '/tmp/tmpdzw_sfs3']
[2022-06-28 14:41:35,723] {standard_task_runner.py:80} INFO - Job 490: Subtask local_to_gcs_task
[2022-06-28 14:41:35,757] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host 181657f59c64
[2022-06-28 14:41:35,810] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_to_gcs
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T00:00:00+00:00
[2022-06-28 14:41:36,128] {python.py:173} INFO - Done. Returned value was: None
[2022-06-28 14:41:36,144] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion_to_gcs, task_id=local_to_gcs_task, execution_date=20200101T000000, start_date=20220628T144135, end_date=20220628T144136
[2022-06-28 14:41:36,175] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-28 14:41:36,234] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-06-28 14:51:49,211] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-28 14:51:49,217] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-28 14:51:49,217] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 14:51:49,217] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-28 14:51:49,217] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 14:51:49,228] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-01-01 00:00:00+00:00
[2022-06-28 14:51:49,232] {standard_task_runner.py:52} INFO - Started process 193 to run task
[2022-06-28 14:51:49,234] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_to_gcs', 'local_to_gcs_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '501', '--raw', '--subdir', 'DAGS_FOLDER/01_data_ingestion_to_gcs.py', '--cfg-path', '/tmp/tmp4wnv6qbh', '--error-file', '/tmp/tmpho_rk85o']
[2022-06-28 14:51:49,235] {standard_task_runner.py:80} INFO - Job 501: Subtask local_to_gcs_task
[2022-06-28 14:51:49,267] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host 3fcea2aa00ee
[2022-06-28 14:51:49,312] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_to_gcs
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T00:00:00+00:00
[2022-06-28 14:51:49,773] {python.py:173} INFO - Done. Returned value was: None
[2022-06-28 14:51:49,782] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion_to_gcs, task_id=local_to_gcs_task, execution_date=20200101T000000, start_date=20220628T145149, end_date=20220628T145149
[2022-06-28 14:51:49,809] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-28 14:51:49,868] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-06-28 14:54:54,439] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-28 14:54:54,445] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-28 14:54:54,445] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 14:54:54,445] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-28 14:54:54,445] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 14:54:54,457] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-01-01 00:00:00+00:00
[2022-06-28 14:54:54,462] {standard_task_runner.py:52} INFO - Started process 186 to run task
[2022-06-28 14:54:54,464] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_to_gcs', 'local_to_gcs_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '510', '--raw', '--subdir', 'DAGS_FOLDER/01_data_ingestion_to_gcs.py', '--cfg-path', '/tmp/tmp4sqymct9', '--error-file', '/tmp/tmppb4qv52p']
[2022-06-28 14:54:54,465] {standard_task_runner.py:80} INFO - Job 510: Subtask local_to_gcs_task
[2022-06-28 14:54:54,501] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host eb1b13b80acd
[2022-06-28 14:54:54,566] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_to_gcs
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T00:00:00+00:00
[2022-06-28 14:54:54,871] {python.py:173} INFO - Done. Returned value was: None
[2022-06-28 14:54:54,881] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion_to_gcs, task_id=local_to_gcs_task, execution_date=20200101T000000, start_date=20220628T145454, end_date=20220628T145454
[2022-06-28 14:54:54,957] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-28 14:54:54,989] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-06-28 15:06:02,643] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-28 15:06:02,649] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-28 15:06:02,649] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 15:06:02,649] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-28 15:06:02,649] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 15:06:02,658] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-01-01 00:00:00+00:00
[2022-06-28 15:06:02,663] {standard_task_runner.py:52} INFO - Started process 203 to run task
[2022-06-28 15:06:02,665] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_to_gcs', 'local_to_gcs_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '524', '--raw', '--subdir', 'DAGS_FOLDER/01_data_ingestion_to_gcs.py', '--cfg-path', '/tmp/tmpujj0rp2j', '--error-file', '/tmp/tmpaay8wswh']
[2022-06-28 15:06:02,665] {standard_task_runner.py:80} INFO - Job 524: Subtask local_to_gcs_task
[2022-06-28 15:06:02,696] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host 375d46b24910
[2022-06-28 15:06:02,741] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_to_gcs
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T00:00:00+00:00
[2022-06-28 15:06:03,173] {python.py:173} INFO - Done. Returned value was: None
[2022-06-28 15:06:03,195] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion_to_gcs, task_id=local_to_gcs_task, execution_date=20200101T000000, start_date=20220628T150602, end_date=20220628T150603
[2022-06-28 15:06:03,239] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-28 15:06:03,267] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-06-28 18:42:19,043] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-28 18:42:19,049] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-06-28 18:42:19,049] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 18:42:19,049] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-28 18:42:19,049] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-28 18:42:19,060] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-01-01 00:00:00+00:00
[2022-06-28 18:42:19,064] {standard_task_runner.py:52} INFO - Started process 389 to run task
[2022-06-28 18:42:19,066] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_to_gcs', 'local_to_gcs_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '565', '--raw', '--subdir', 'DAGS_FOLDER/01_data_ingestion_to_gcs.py', '--cfg-path', '/tmp/tmp9llhcn99', '--error-file', '/tmp/tmpjcp6qew6']
[2022-06-28 18:42:19,067] {standard_task_runner.py:80} INFO - Job 565: Subtask local_to_gcs_task
[2022-06-28 18:42:19,101] {task_command.py:370} INFO - Running <TaskInstance: data_ingestion_to_gcs.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host 9f709a2aaee5
[2022-06-28 18:42:19,150] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_to_gcs
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T00:00:00+00:00
[2022-06-28 18:42:19,738] {python.py:173} INFO - Done. Returned value was: None
[2022-06-28 18:42:19,760] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_ingestion_to_gcs, task_id=local_to_gcs_task, execution_date=20200101T000000, start_date=20220628T184219, end_date=20220628T184219
[2022-06-28 18:42:19,800] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-28 18:42:19,844] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
